---
fixtures:
  repositories:
    apache: https://github.com/simp/pupmod-simp-apache
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders: https://github.com/simp/augeasproviders
    augeasproviders_base: https://github.com/simp/augeasproviders_base
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet: https://github.com/simp/augeasproviders_puppet
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pam: https://github.com/simp/pupmod-simp-pam
    concat: https://github.com/simp/puppetlabs-concat
    pki: https://github.com/simp/pupmod-simp-pki
    rsync: https://github.com/simp/pupmod-simp-rsync
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simpcat: https://github.com/simp/pupmod-simp-simpcat
#FIXME:  Revert to master, once SIMP-3280 is merged
#    simplib: https://github.com/simp/pupmod-simp-simplib
    simplib: 
      repo: https://github.com/lnemsick-simp/pupmod-simp-simplib
      branch: SIMP-3280
    stdlib: https://github.com/simp/puppetlabs-stdlib
    puppet_enterprise:
      repo: https://github.com/simp/pupmod-mock-puppet_enterprise
      ref: 0.3.0
    puppet_authorization: https://github.com/simp/puppetlabs-puppet_authorization.git
  symlinks:
    pupmod: "#{source_dir}"
