---
fixtures:
  repositories:
    apache:
      repo: https://github.com/simp/pupmod-simp-apache
      branch: 5.X
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    augeasproviders:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders
    augeasproviders_base:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_base
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_puppet
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    inifile:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-inifile
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    rsync:
      repo: https://github.com/simp/pupmod-simp-rsync
      branch: 5.X
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    pupmod: "#{source_dir}"
