---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet: https://github.com/simp/augeasproviders_puppet
    cron_core:
      repo: https://github.com/simp/pupmod-puppetlabs-cron_core
      puppet_version: ">= 6.0.0"
    haveged: https://github.com/simp/pupmod-simp-haveged
    incron: https://github.com/simp/pupmod-simp-incron
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables
    concat: https://github.com/simp/puppetlabs-concat
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core
      puppet_version: ">= 6.0.0"
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    pam: https://github.com/simp/pupmod-simp-pam
    puppet_enterprise:
      repo: https://github.com/simp/pupmod-mock-puppet_enterprise
      ref: 0.3.0
    puppet_authorization:
      repo: https://github.com/simp/puppetlabs-puppet_authorization
      ref: 0.5.0

    # Fixtures needed for the acceptance test
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    sudo: https://github.com/simp/pupmod-simp-sudo
  symlinks:
    pupmod: "#{source_dir}"
