---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet: https://github.com/simp/augeasproviders_puppet
    cron_core:
      repo: https://github.com/simp/pupmod-puppetlabs-cron_core
      puppet_version: ">= 6.0.0"
    haveged: https://github.com/simp/pupmod-simp-haveged
    incron: https://github.com/simp/pupmod-simp-incron
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core
      puppet_version: ">= 6.0.0"
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat:
      repo: https://github.com/simp/puppetlabs-concat
      ref: 5.3.0
    hocon:
      repo: https://github.com/puppetlabs/puppetlabs-hocon
      ref: 1.0.1
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    pam: https://github.com/simp/pupmod-simp-pam
    puppet_enterprise:
      repo: https://github.com/simp/pupmod-mock-puppet_enterprise
      ref: 0.3.0
    puppet_authorization:
      repo: https://github.com/simp/puppetlabs-puppet_authorization
      ref: 0.5.0

    # Fixtures needed for the acceptance test
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    sudo: https://github.com/simp/pupmod-simp-sudo
  symlinks:
    pupmod: "#{source_dir}"
