---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet: https://github.com/simp/augeasproviders_puppet
    haveged: https://github.com/simp/pupmod-simp-haveged
    incron: https://github.com/simp/pupmod-simp-incron
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    pam: https://github.com/simp/pupmod-simp-pam
    puppet_enterprise:
      repo: https://github.com/simp/pupmod-mock-puppet_enterprise
      ref: 0.3.0
    puppet_authorization:
      repo: https://github.com/simp/puppetlabs-puppet_authorization
      ref: 0.4.0

    # Fixtures needed for the acceptance test
    # apache: https://github.com/simp/pupmod-simp-apache
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    # logrotate: https://github.com/simp/pupmod-simp-logrotate
    # oddjob: https://github.com/simp/pupmod-simp-oddjob
    # pki: https://github.com/simp/pupmod-simp-pki
    # rsync: https://github.com/simp/pupmod-simp-rsync
    # rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    # simpcat: https://github.com/simp/pupmod-simp-simpcat
    # simp_options: https://github.com/simp/pupmod-simp-simp_options
    # stunnel: https://github.com/simp/pupmod-simp-stunnel
    sudo: https://github.com/simp/pupmod-simp-sudo
    # tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    pupmod: "#{source_dir}"
