---
fixtures:
  repositories:
    apache: "https://github.com/simp/pupmod-simp-apache"
    auditd: "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders:
      repo: "https://github.com/simp/augeasproviders"
    augeasproviders_base:
      repo: "https://github.com/simp/augeasproviders_base"
      branch: "simp-master"
    augeasproviders_core:
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub:
      repo: "https://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    augeasproviders_puppet:
      repo: "https://github.com/simp/augeasproviders_puppet"
      branch: "simp-master"
    compliance_markup: "https://github.com/simp/pupmod-simp-compliance_markup"
    haveged:
      repo: "https://github.com/simp/puppet-haveged"
      branch: "simp-master"
    simpcat: "https://github.com/simp/pupmod-simp-simpcat"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    inifile:
      repo: "https://github.com/simp/puppetlabs-inifile"
      branch: "simp-master"
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    logrotate: "https://github.com/simp/pupmod-simp-logrotate"
    pki: "https://github.com/simp/pupmod-simp-pki"
    rsync: "https://github.com/simp/pupmod-simp-rsync"
    rsyslog: "https://github.com/simp/pupmod-simp-rsyslog"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
  symlinks:
    pupmod: "#{source_dir}"
