<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  puppet.el7:
    roles:
      - default
      - simp_master
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 4608
    vagrant_cpus: 2

  puppet.el8:
    roles:
      - simp_master
    platform: el-8-x86_64
    box: centos/8
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 4608
    vagrant_cpus: 2

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
