<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  puppet:
    roles:
      - server # Mandatory
      - master
      - default
      - simp_server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 4608
    vagrant_cpus: 2
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: 'https://packagecloud.io/simp-project/6_X/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
      simp_dependencies:
        baseurl: 'https://packagecloud.io/simp-project/6_X_Dependencies/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://yum.puppet.com/RPM-GPG-KEY-puppetlabs
          - https://yum.puppet.com/RPM-GPG-KEY-puppet
          - https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-96
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  agent:
    roles:
      - agent
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: 'https://packagecloud.io/simp-project/6_X/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
      simp_dependencies:
        baseurl: 'https://packagecloud.io/simp-project/6_X_Dependencies/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://yum.puppet.com/RPM-GPG-KEY-puppetlabs
          - https://yum.puppet.com/RPM-GPG-KEY-puppet
          - https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-96
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
